# Site settings
title: funcman's blog
email: hyq1986@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  一个游戏程序员，但是现在正在做iOS应用。<br/>
  欢迎使用<a href='https://itunes.apple.com/app/id938688461'>小米运动</a>！
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://funcman.github.io" # the base hostname & protocol for your site
twitter_username: funcman
github_username: funcman

# Build settings
markdown: kramdown
